import React, { useState, useEffect, useRef } from 'react';
import { X } from 'lucide-react';

const initialFileContents = {
  // Test file - PII data
  'PIIdata.csv': `Customer_name,Customer_phone_number,Customer_landmark
John Smith,555-0101,Central Park
Maria Garcia,555-0102,Empire State Building
Ahmed Hassan,555-0103,Brooklyn Bridge
Li Wei,555-0104,Times Square
Sarah Johnson,555-0105,Statue of Liberty
Raj Patel,555-0106,Grand Central
Elena Rodriguez,555-0107,Madison Square
Yuki Tanaka,555-0108,Wall Street
Mohammed Ali,555-0109,Rockefeller Center`,

  // Boston Housing dataset files
  'boston_housing/boston_housing.py': `"""
Boston Housing Price Prediction
Dataset: Boston Housing Dataset (scikit-learn)
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pickle

def load_data():
    """Load Boston housing dataset"""
    boston = load_boston()
    df = pd.DataFrame(boston.data, columns=boston.feature_names)
    df['MEDV'] = boston.target
    return df, boston

def train_model(X_train, y_train):
    """Train linear regression model"""
    model = LinearRegression()
    model.fit(X_train, y_train)
    return model

def evaluate_model(model, X_test, y_test):
    """Evaluate model performance"""
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"R² Score: {r2:.2f}")
    return mse, r2

def save_model(model, filepath='boston_housing/boston_housing.pkl'):
    """Save trained model to pickle file"""
    with open(filepath, 'wb') as f:
        pickle.dump(model, f)
    print(f"Model saved to {filepath}")

def main():
    # Load data
    df, boston = load_data()
    print(f"Dataset shape: {df.shape}")
    print("\\nFeature names:", boston.feature_names.tolist())
    print("\\nTarget: MEDV (Median value of homes in $1000s)")
    
    # Prepare features and target
    X = df.drop('MEDV', axis=1)
    y = df['MEDV']
    
    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    
    # Train model
    print("\\nTraining model...")
    model = train_model(X_train, y_train)
    
    # Evaluate
    print("\\nModel Evaluation:")
    evaluate_model(model, X_test, y_test)
    
    # Feature importance
    feature_importance = pd.DataFrame({
        'feature': boston.feature_names,
        'coefficient': model.coef_
    }).sort_values('coefficient', key=abs, ascending=False)
    
    print("\\nTop 5 Most Important Features:")
    print(feature_importance.head())
    
    # Save model
    save_model(model)

if __name__ == "__main__":
    main()`,

  'boston_housing/boston_housing.pkl': `# This is a binary pickle file
# To load: 
# import pickle
# with open('boston_housing/boston_housing.pkl', 'rb') as f:
#     model = pickle.load(f)
# 
# Note: This is a placeholder. The actual .pkl file would be 
# generated by running boston_housing.py and contains a 
# trained scikit-learn LinearRegression model.
#
# File format: Binary pickle (not human-readable)`,

  'boston_housing/README.md': `# Boston Housing Price Prediction

## Dataset Description
The Boston Housing dataset contains information about housing in Boston suburbs.

### Features (13 total):
- **CRIM**: Per capita crime rate
- **ZN**: Proportion of residential land zoned for large lots
- **INDUS**: Proportion of non-retail business acres
- **CHAS**: Charles River dummy variable (1 if tract bounds river; 0 otherwise)
- **NOX**: Nitric oxides concentration (parts per 10 million)
- **RM**: Average number of rooms per dwelling
- **AGE**: Proportion of owner-occupied units built before 1940
- **DIS**: Weighted distances to employment centers
- **RAD**: Index of accessibility to radial highways
- **TAX**: Property tax rate per $10,000
- **PTRATIO**: Pupil-teacher ratio by town
- **B**: 1000(Bk - 0.63)² where Bk is the proportion of Black residents
- **LSTAT**: Percentage of lower status population

### Target:
- **MEDV**: Median value of owner-occupied homes in $1000s

## Files
- \`boston_housing.py\`: Main script for training and evaluation
- \`boston_housing.pkl\`: Trained model (generated after running the script)

## Usage
\`\`\`python
python boston_housing/boston_housing.py
\`\`\`

## Ethical Considerations
⚠️ **Important**: This dataset contains the 'B' feature which relates to racial demographics. 
This raises ethical concerns about potential bias and discrimination in housing price predictions.
Modern usage of this dataset should carefully consider these implications.`
};

export function EditorArea({ openFile, dataSciencePanelOpen, onFileContentsChange, externalFileContents }) {
  const [fileContents, setFileContents] = useState(initialFileContents);
  const [content, setContent] = useState('');
  const textareaRef = useRef(null);
  const lineNumbersRef = useRef(null);

  // Merge initial files with external uploaded files
  useEffect(() => {
    if (externalFileContents) {
      setFileContents(prev => ({
        ...prev,
        ...externalFileContents
      }));
    }
  }, [externalFileContents]);

  useEffect(() => {
    if (openFile) {
      setContent(fileContents[openFile] || '// File not found');
    } else {
      setContent('');
    }
  }, [openFile, fileContents]);

  useEffect(() => {
    onFileContentsChange(fileContents);
  }, [fileContents, onFileContentsChange]);

  const handleContentChange = (e) => {
    const newContent = e.target.value;
    setContent(newContent);
    if (openFile) {
      setFileContents(prev => ({
        ...prev,
        [openFile]: newContent
      }));
    }
  };

  const handleScroll = (e) => {
    if (lineNumbersRef.current) {
      lineNumbersRef.current.scrollTop = e.currentTarget.scrollTop;
    }
  };

  const lineCount = content.split('\n').length;
  const lineNumbers = Array.from({ length: lineCount }, (_, i) => i + 1);

  // Styles
  const containerStyle = {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#1e1e1e',
  };

  const tabsContainerStyle = {
    height: '36px',
    backgroundColor: '#252526',
    display: 'flex',
    alignItems: 'center',
    borderBottom: '1px solid #3e3e42',
  };

  const tabStyle = {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    paddingTop: '4px',
    paddingBottom: '4px',
    backgroundColor: '#1e1e1e',
    borderRight: '1px solid #3e3e42',
  };

  const tabTextStyle = {
    fontSize: '14px',
    color: '#cccccc',
  };

  const closeButtonStyle = {
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '4px',
    padding: '2px',
    cursor: 'pointer',
    color: '#cccccc',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.2s ease',
  };

  const editorContentStyle = {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
  };

  const lineNumbersStyle = {
    backgroundColor: '#1e1e1e',
    color: '#858585',
    textAlign: 'right',
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingRight: '16px',
    paddingLeft: '8px',
    fontFamily: 'monospace',
    fontSize: '14px',
    overflow: 'hidden',
    userSelect: 'none',
    minWidth: '3rem',
  };

  const lineNumberStyle = {
    lineHeight: '1.5rem',
  };

  const textareaStyle = {
    flex: 1,
    backgroundColor: '#1e1e1e',
    color: '#cccccc',
    padding: '16px',
    fontFamily: 'monospace',
    fontSize: '14px',
    resize: 'none',
    outline: 'none',
    overflow: 'auto',
    border: 'none',
    lineHeight: '1.5rem',
    tabSize: 4,
  };

  return (
    <div style={containerStyle}>
      {/* Tabs */}
      <div style={tabsContainerStyle}>
        {openFile && (
          <div style={tabStyle}>
            <span style={tabTextStyle}>{openFile}</span>
            <button
              style={closeButtonStyle}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = '#2a2d2e';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = 'transparent';
              }}
            >
              <X size={14} />
            </button>
          </div>
        )}
      </div>

      {/* Editor content */}
      <div style={editorContentStyle}>
        {/* Line numbers */}
        <div ref={lineNumbersRef} style={lineNumbersStyle}>
          {lineNumbers.map((num) => (
            <div key={num} style={lineNumberStyle}>
              {num}
            </div>
          ))}
        </div>

        {/* Editable text area */}
        <textarea
          ref={textareaRef}
          value={content}
          onChange={handleContentChange}
          onScroll={handleScroll}
          spellCheck={false}
          style={textareaStyle}
        />
      </div>
    </div>
  );
}